# setup-app.yml
---
- hosts: webservers
  become: true
  vars:
    path_to_app: '/var/www/html'
  tasks:
    - name: Upload application files
      copy:
        src: ../index.php
        dest: '{{ path_to_app }}'
        mode: 0755

    - name: Create simple info page
      copy:
        dest: '{{ path_to_app }}/info.php'
        content: '<h1>Webserver info: {{ ansible_hostname }}</h1>'

    - name: See directory content
      command: ls -la {{ path_to_app }}
      register: dir_content

    - name: Debug directory content
      debug:
        msg: '{{ dir_content }}'

    - name: Configure php.ini file
      lineinfile:
        path: /etc/php.ini
        regexp: ^short_open_tag
        line: 'short_open_tag=on'
      notify: Restart apache

  handlers:
    - name: Restart apache
      service: name=httpd state=restarted
