---
# tasks file for ./roles/webservers

- name: Upload application files
  copy:
    src: ../files/index.php
    dest: '{{ path_to_app }}'
    mode: 0755
  when: upload_var == 'yes'
  tags: upload

- name: Create simple info page
  copy:
    dest: '{{ path_to_app }}/info.php'
    content: '<h1>Webserver info: {{ ansible_hostname }}</h1>'
  when: create_var == 'yes'
  tags: create

- name: See directory content
  command: ls -la {{ path_to_app }}
  register: dir_content

- name: Debug directory content
  debug:
    msg: '{{ dir_content }}'

- name: Configure php.ini file
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=on'
  notify: Restart apache
